version: "3"
services:
  nginx-lb:
    networks:
      mynet:
        ipv4_address: 172.18.0.5
    image: "nginx"
    container_name: "nginxP"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/loadbalancer/include:/etc/nginx/include:ro
      - ./nginx/loadbalancer/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    depends_on:
      - bingo
      - bingo_2
      - bingo_3
      - bingo_4
    ports:
      - "80:80"
      - "443:443"
    restart: always

  bingo:
    image: "bingo"
    container_name: "bingo_1"
    ports:
    - 81:21477
    networks:
      mynet:
        ipv4_address: 172.18.0.6
    volumes:
    - ./data:/opt/bongo/logs/d21f3f8deb
    restart: always

  bingo_2:
    image: "bingo"
    container_name: "bingo_2"
    ports:
    - 82:21477
    networks:
      mynet: 
        ipv4_address: 172.18.0.7
    volumes:
    - ./data2:/opt/bongo/logs/d21f3f8deb
    restart: always

  bingo_3:
    image: "bingo"
    container_name: "bingo_3"
    ports:
    - 83:21477
    networks:
      mynet:
        ipv4_address: 172.18.0.8
    volumes:
    - ./data3:/opt/bongo/logs/d21f3f8deb
    restart: always

  bingo_4:
    image: "bingo"
    container_name: "bingo_4"
    ports:
    - 84:21477
    networks:
      mynet:
        ipv4_address: 172.18.0.9
    volumes:
    - ./data4:/opt/bongo/logs/d21f3f8deb
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_USER: ${POSTGRES_USER:-bingo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Gobin}
      PGDATA: /data/postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      mynet:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

  postgres2:
    container_name: postgres_s
    image: postgres
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_USER: ${POSTGRES_USER:-bingo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Gobin}
      PGDATA: /data/postgres
      REPLICATE_FROM: 'postgres'
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
       - postgres2:/data/postgres
    ports:
      - "5433:5432"
    networks:
      mynet:
        ipv4_address: 172.18.0.3
    restart: unless-stopped

volumes:
  postgres:
  postgres2:
  pgadmin:
  data:
  data2:
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
        - gateway: 172.18.0.1

